### ISSUE TITLE
Password typo generates an error

### ISSUE THREAD

**Issue by GianniCristian** [ibamacsr/sentinelsat#11]
Hi All,

I was trying to use sentinelsat via command line using this example found on a website:

sentinel search -f -s 20140101 -e 20151004 -q "producttype=GRD" username password vietnam_coast.geojson

I have used the same geojson to accomplish the same request. Unfortunately, my password end with '....&a' and once I have done the command I get:

'a' is not recognized as an internal or external command.

If I just let usernamen and password I get, of course, another error but different: 

simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In this case seems the error is linked to the json file but I have actually copy and paste this file: 

https://github.com/Fernerkundung/fernerkundung.github.io/commit/c59a2028d4af93240a79fe3428fa5ea774e0d286

I have also tried to use the python code:

from sentinelsat.sentinel import SentinelAPI

api = SentinelAPI('username','......&a')
api.query('-4.53 29.85, 26.75 29.85, 26.75 46.80,-4.53 46.80,-4.53 29.85')

but I get 502 error.

Furhtermore, it is implemented a way to obtain the footprint of the geojson also in Python script and not just by command line? 

Thanks!

**Comment by Fernerkundung** [comment]
Since you are referring to a [tutorial](http://fernerkundung.github.io/download-sentinel-images-with-python/) I wrote let me try to answer what I can.

*'a' is not recognized as an internal or external command.*
This error is likely caused by the `&` in your password and the handling of passwords internally requires a code change to account for special characters.

*simplejson.scanner.JSONDecodeError:*
This error is not from parsing the `vietnam_coast.geojson` search polygon but rather from decoding the response of the SciHub server.

*502 error*
From the Python interface your username and password work but ESAs servers are not responding properly. I've hat multiple `502` and `503` errors in the last time. Everytime I checked the SciHub website it told me the SciHub is unreachable at the moment. In other words - you have to wait and try again.

*obtain the footprint of the geojson also in Python script*
Sure it is. The `SentinelAPI` class has a method `get_footprints()` which returns a `geojson.FeatureCollection`.

````python
api = SentinelAPI('username','......&a')
api.query('-4.53 29.85, 26.75 29.85, 26.75 46.80,-4.53 46.80,-4.53 29.85')

footprints = api.get_footprints()
````

**Comment by GianniCristian** [comment]
Thanks for the answer. I will keep trying using the Python script. About the geojson, I was wondering if it is possible to get the footpring using a geojson as input, and so something like:

api = SentinelAPI('username','......&a')
geojson = 'C:\...\vietnam_coast.geojson'
footprint = api.load_footprint(geojson)
api.query(footprint)

Is is possible? 

Thanks!

**Comment by Fernerkundung** [comment]
You can always use the `get_coordinates` function to extract the coordinates from the search geojson file.

````python
from sentinelsat import SentinelAPI, get_coordinates

search_polygon = get_coordinates("/path/to/search_polygon.geojson")

api = SentinelAPI("user", "password")
api.query(area=search_polygon, ...)

result_footprints = api.get_footprints()
````

**Comment by GianniCristian** [comment]
Perfect! I have done the same but the following message comes out:

'No products found in this query.'

No more 502 error but I get this problem. Can you please send me a json which works on your computer? I don't know if I'm missing something...

**Comment by willemarcel** [comment]
Hi @GianniCristian,

You can use geojson.io to write geojson files. We only support to read one polygon in each file.

We run the tests using this geojson: https://github.com/ibamacsr/sentinelsat/blob/master/tests/map.geojson

**Comment by GianniCristian** [comment]
Perfect! Using your geojson, it works! So, there was a problem using my geojson. 

Thanks!

**Comment by Fernerkundung** [comment]
I just tested passwords with different special characters. From the command line you have to wrap them in parenthesis and everything works. The only limitation is that your password may not contain parenthesis.

`sentinel search -q "producttype=GRD" username "&p@ssw0r|)" map.geojson"`

This should solve the issue with your password.
