### ISSUE TITLE
-s option reads ingested not acquired date

### ISSUE THREAD

**Issue by unnic** [ibamacsr/sentinelsat#32]
Using the -s option including a date limits the download to the time period where the image was uploaded to the hub, not when it was acquired.

`sentinel search -d -s 20151219 -c 30 --md5 username password roi.geojson`

> Search and download all Sentinel-2 products with less than 30% cloud cover **acquired** since 2015-12-19. 

E.g: using -s 20160525 will download data aquired from 2015 which was just added (ingested) to the Sentinel-2 hub this month.

**Comment by willemarcel** [comment]
Hi @unnic,

Generally the ingestion date and the upload date are almost the same, but maybe it was a bad option to set the start date as the upload date. For now, you can filter the ingestion date using the **-q** option, for example: **-q ingestiondate=[2014-01-01T00:00:00.000Z TO NOW]**

**Comment by unnic** [comment]
@willemarcel 
no, the ingestion date and the upload date can be quite different because ESA has been uploading 2015 data for the last few weeks. But thanks for pointing out the -q option, that'll work.

**Comment by Fernerkundung** [comment]
This is a valid point. I think the expected behaviour of sentinelsat should be to query the acquisition not the upload date.

**Comment by pidancier** [comment]
Hi guys,
If you prefer query scihub by aquisition date instead of system ingestion date, you could replace
```
ingestionDate:[2016-05-30T00:00:00Z TO 2016-05-31T00:00:00Z]
```
by
```
beginPosition:[2016-05-30T00:00:00Z TO 2016-05-31T00:00:00Z]
```
or
```
endPosition:[2016-05-30T00:00:00Z TO 2016-05-31T00:00:00Z]
```

endPostion and beginPosition are mentioned at https://scihub.copernicus.eu/userguide/3FullTextSearch

**Comment by Fernerkundung** [comment]
Great hint @pidancier!

I created a PR to address this issue. With this sentinelsat now queries the beginPosition instead of the ingestionDate - just like described in the docs.

This also enables us to search for scenes *acquired* in 2015 which have been *ingested* in 2016. This could be useful to find "missing" scenes that ESA ingested much later than their aquisition time:

`sentinel search -s 20150101 -e 20151231 -c 30 -q "ingestiondate=[2016-01-01T00:00:00.000Z TO NOW]" username password map.geojson`
