### ISSUE TITLE
HTTP authentication required

### ISSUE THREAD

**Issue by unnic** [ibamacsr/sentinelsat#45]
Hello,

i updated sentinelsat and tried to run the example `sentinel search --sentinel2 <user> <password> <poly.geojson>`

I get an error:

```
* * *

**type** Status report

**message** _Full authentication is required to access this resource_

**description** _This request requires HTTP authentication._

* * *

### Apache Tomcat/7.0.47
```

certifi is installed and updated

edit: same via the python api

**Comment by fradaloisio** [comment]
If you are using the dedicated Sentinel-2 hub (https://scihub.copernicus.eu/s2/) read this news
https://scihub.copernicus.eu/news/News00097

**Comment by unnic** [comment]
I assume your code example is using the default https://scihub.copernicus.eu/apihub/

**Comment by Fernerkundung** [comment]
I could reproduce this error whenever I used a wrong username/password combination as the error states. Can you make sure that your account credentials work on the web-frontend of https://scihub.copernicus.eu/dhus/?

```
...
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://scihub.copernicus.eu/apihub/search?format=json&rws=15000
...
```

**Comment by unnic** [comment]
The account credentials are ok, i can log in on the web-frontend. 
I dont get 

'requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://scihub.copernicus.eu/apihub/search?format=json&rws=15000'

but

'sentinelsat.sentinel.SentinelAPIError: (HTTP status: 401, code: None) # HTTP Status 401 - Full authentication is required to access this resource'

Apperently the account is not enabled to access the API hub, i tried an older account and it works with that one. 
Thanks again for your input.

**Comment by Fernerkundung** [comment]
afaik the sync of accounts between scihub and apihub happens "periodically", as stated by ESA, but I couldn't find any documentation on how often the sync.

Was this perhaps a newly created account?

**Comment by unnic** [comment]
I created it in march and assumed it was old enough to already be in the list...

**Comment by NicWayand** [comment]
I am getting the same auth errors. I created my account Oct 25, 2016.  Any idea how long I have to wait? This is quite frustrating to have to wait.

**Comment by davidbernat** [comment]
Same errors here.

**Comment by Fernerkundung** [comment]
@davidbernat can you please provide a bit more information regarding the error, i.e.:

- How long between account creation on `dhus` and trying to access `apihub`?
- Special characters in your password that might be causing trouble (see docs)? Maybe try changing the password temporarily to rule this out.
- Which DHuS are you trying to access?
- Limited to 1 machine or limited to 1 account?

**Comment by davidbernat** [comment]
Hi Kersten,

The problem seems to be a result of API endpoint and credentials
propagation.
Using api_url="https://scihub.copernicus.eu/dhus/" works.

Might be helpful if you add two (rather important imo) details to the front
page of the Readme.
1. A brief discussion of the credentials propagation problem, i.e., that
the dhus endpoint will work for a while (and maybe why two endpoints)
2. A link to the signup for credentials. This may seem obvious, but nowhere
in the documents or readme does the reader ever learn where they should go
sign up. This becomes even more confusing when SentinelHub has multiple
signups etc. And then, you can imagine, when credentials don't work for one
endpoint there is significant wtf and confusion. My two cents from being in
the sat field for a few years.

Thanks for the API!
Cheers,
David



On Fri, Jan 31, 2020 at 8:21 AM Kersten <notifications@github.com> wrote:
>
> @davidbernat can you please provide a bit more information regarding the
error, i.e.:
>
> How long between account creation on dhus and trying to access apihub?
> Special characters in your password that might be causing trouble (see
docs)? Maybe try changing the password temporarily to rule this out.

**Comment by j08lue** [comment]
RTD https://sentinelsat.readthedocs.io/en/stable/common_issues.html 😉

**Comment by davidbernat** [comment]
The top line examples don't function out of the box. If I don't find it in
30 minutes of Google searching and reading the docs and searching the
GitHub issues its' not prominently placed enough ;-)

Also, if you check the GitHub issue this credential problem refers to
you'll see that its dialogue remains inconclusive to key questions. ;-)

GTG Phone call w/ Planet about how their images "really are" 3m. ;-)

Cheers, ;-)
David

**Comment by davidbernat** [comment]
This is an open source project, correct? I can make a pull request and edit
the document, should you want that?

**Comment by Fernerkundung** [comment]
Sure - PRs of any kind are encouraged :+1: 

Have you found the source of the authentication issues or what are you proposing to add to the documentation?
